# Generated by Django 5.0.14 on 2026-02-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('marketplace', '0004_category_remove_item_image_item_shipping_cents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='interested_profiles', to='marketplace.category'),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
